# -*- coding: utf-8 -*-
"""CTD_prework_wilnelliediaz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkv32LRpQ21zimS0cOvpe9g040Mgld3I
"""

# name and books read this year

name= input('Enter your name: ')
books= int(input('How many books have you read this year: '))

if books >=15:
  print("hello "  + name +  " wow " + str(books)  + " books, is very impressive.")

else:
 print("hello " + name +  " that's a great start " + str(books) + " books, keep it up.")


 # example run 1
 # input: nellie, 20
 # output: wow 20 books is very impressive.
 # example run 2
 # input: nellie, 8
 # output: thats a great start 8 books, keep it up.